version: '3.8'

services:
  # Database service for development
  postgres:
    image: postgres:15-alpine
    container_name: auracase-db-dev
    environment:
      POSTGRES_DB: auracase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - auracase-dev-network

  # Application service for development
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: auracase-app-dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password123@postgres:5432/auracase
      - JWT_SECRET=dev-jwt-secret-change-in-production
      - NEXTAUTH_URL=http://localhost:3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - postgres
    networks:
      - auracase-dev-network
    command: >
      sh -c "
        echo 'Waiting for database to be ready...' &&
        npx prisma db push &&
        npx prisma db seed &&
        npm run dev
      "

volumes:
  postgres_data_dev:

networks:
  auracase-dev-network:
    driver: bridge
